# Generated by Django 5.1.4 on 2024-12-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slyg',
            new_name='slug',
        ),
    ]
